#!/usr/bin/env python3

import json
import locale
import sys


def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"sales": 0}
  most_popular_year = {}
  for item in data:

    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item

    # TODO: also handle max sales
    if item["total_sales"] > max_sales["sales"]:
      item["sales"] = item["total_sales"]
      max_sales = item

    # TODO: also handle most popular car_year
    if item["car"]["car_year"] in most_popular_year:
      most_popular_year[f"""{item["car"]["car_year"]}"""] = 0
    else:
      most_popular_year[f"""{item["car"]["car_year"]}"""] =+ item["total_sales"]
      # most_popular_year[f"""{item["car"]["car_year"]}"""] += 1

  # Had a tought time getting the sorted() method to work in order to get the most popular year:
  most_popular_year_sorted = dict(sorted(most_popular_year.items(), key=lambda item: item[1], reverse = True))
  most_popular_year_stat = list(most_popular_year_sorted.items())[0]


  summary = [
    "The {} generated the most revenue: ${}. \n Furthermore, the most sales was: {} cars, a {} {} year: {}, \n and the most popular year was: {}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"], max_sales["sales"], max_sales["car"]["car_make"], max_sales["car"]["car_model"], max_sales["car"]["car_year"], most_popular_year_stat[0]),
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("../car_sales.json")
  summary = process_data(data)
  print(summary)
  # TODO: turn this into a PDF report

  # TODO: send the PDF report as an email attachment


if __name__ == "__main__":
  main(sys.argv)
